// Generated from "ast_node_def.ini". DO NOT edit.

#define OW_AST_NODE_LIST \
	ELEM(NilLiteral)      \
	ELEM(BoolLiteral)     \
	ELEM(IntLiteral)      \
	ELEM(FloatLiteral)    \
	ELEM(SymbolLiteral)   \
	ELEM(StringLiteral)   \
	ELEM(Identifier)      \
	ELEM(AddExpr)         \
	ELEM(SubExpr)         \
	ELEM(MulExpr)         \
	ELEM(DivExpr)         \
	ELEM(RemExpr)         \
	ELEM(ShlExpr)         \
	ELEM(ShrExpr)         \
	ELEM(BitAndExpr)      \
	ELEM(BitOrExpr)       \
	ELEM(BitXorExpr)      \
	ELEM(EqlExpr)         \
	ELEM(AddEqlExpr)      \
	ELEM(SubEqlExpr)      \
	ELEM(MulEqlExpr)      \
	ELEM(DivEqlExpr)      \
	ELEM(RemEqlExpr)      \
	ELEM(ShlEqlExpr)      \
	ELEM(ShrEqlExpr)      \
	ELEM(BitAndEqlExpr)   \
	ELEM(BitOrEqlExpr)    \
	ELEM(BitXorEqlExpr)   \
	ELEM(EqExpr)          \
	ELEM(NeExpr)          \
	ELEM(LtExpr)          \
	ELEM(LeExpr)          \
	ELEM(GtExpr)          \
	ELEM(GeExpr)          \
	ELEM(AndExpr)         \
	ELEM(OrExpr)          \
	ELEM(AttrAccessExpr)  \
	ELEM(MethodUseExpr)   \
	ELEM(PosExpr)         \
	ELEM(NegExpr)         \
	ELEM(BitNotExpr)      \
	ELEM(NotExpr)         \
	ELEM(TupleExpr)       \
	ELEM(ArrayExpr)       \
	ELEM(SetExpr)         \
	ELEM(MapExpr)         \
	ELEM(CallExpr)        \
	ELEM(SubscriptExpr)   \
	ELEM(LambdaExpr)      \
	ELEM(ExprStmt)        \
	ELEM(BlockStmt)       \
	ELEM(ReturnStmt)      \
	ELEM(MagicReturnStmt) \
	ELEM(ImportStmt)      \
	ELEM(IfElseStmt)      \
	ELEM(ForStmt)         \
	ELEM(WhileStmt)       \
	ELEM(FuncStmt)        \
	ELEM(Module)          \
// ^^^ OW_AST_NODE_LIST ^^^
